

//ATTENTION
//this is normally found in main.c of Main ram

//THIS all needs to go away once the main.c object code are generated.

#define MAX_ENEMIES 8
struct Entity active_enemies[MAX_ENEMIES];

//#include "newEnemy.h"

#define ENEMY_EYE		22
#define ENEMY_CANNON_DOWN_LEFT	23
#define ENEMY_CANNON_DOWN_RIGHT 24
#define ENEMY_CANNON_UP		25
#define ENEMY_1			29
#define ENEMY_KAMIKAZE		33
#define ENEMY_FURBY		37
#define ENEMY_FINAL4_EYE        26
#define ENEMY_POWERUP		56
#define ENEMY_SHIP1		22
#define ENEMY_SHIP2		23
#define ENEMY_SHIP3		24
#define ENEMY_SHIP4		25
#define ENEMY_TURRET		26
#define ENEMY_FINAL1_SHOOT	38
#define ENEMY_ASTEROID		22
#define ENEMY_TRASH1		26
#define ENEMY_TRASH2		27
#define ENEMY_TRASH3		28
#define ENEMY_TRASH4		29
#define ENEMY_TRASH5		30
#define ENEMY_SALTARIN		22
#define ENEMY_CASCO		26
#define ENEMY_EGG		30
#define ENEMY_UGLYGUY		40
#define ENEMY_1_BIS		46
#define ENEMY_SHIP2_BIS		22
#define ENEMY_SHIP3_BIS		23
#define ENEMY_SALTARIN_BIS	24
#define ENEMY_CASCO_BIS		28
#define ENEMY_EGG_BIS		32
#define ENEMY_UGLYGUY_BIS	42
#define ENEMY_SHIP1_LEVEL7	22
#define ENEMY_SHIP2_LEVEL7	23
#define ENEMY_SHIP3_LEVEL7	24
#define ENEMY_SHIP4_LEVEL7	25
#define ENEMY_TURRET_LEVEL7	26
#define ENEMY_PACOSHIP_1	29
#define ENEMY_PACOSHIP_2	30
#define ENEMY_FINAL1_LEVEL7_UL	31
#define ENEMY_FINAL1_LEVEL7_UR	32
#define ENEMY_FINAL1_LEVEL7_DL	33
#define ENEMY_FINAL1_LEVEL7_DR	34


// Behaviors are directly associated to the enemy sprite with the same index

#define BEHAV_DO_NOTHING 0
#define BEHAV_SHOOT_LEFT 1
#define BEHAV_SHOOT_TARGET 2
#define BEHAV_SHOOT_TARGET_LEFT 3
#define BEHAV_SHOOT_TARGET_RIGHT 4
#define BEHAV_POWERUP 	5
#define BEHAV_TURRET 	6
#define BEHAV_SHOOT_LEFT_Y 7
#define BEHAV_SHOOT_LEFT_WAIT 8
#define BEHAV_ASTEROID 	9
#define BEHAV_SALTARIN 	10
#define BEHAV_CASCO 	11
#define BEHAV_EGG	12
#define BEHAV_UGLYGUY	13
#define BEHAV_SALTARIN_BIS 	14
#define BEHAV_CASCO_BIS 	15
#define BEHAV_FOLLOW	16
#define BEHAV_FINAL1_L7	17




	// Enemy sprites
	unsigned char enemy_sprites[] =
	{
		ENEMY_EYE,
		ENEMY_CANNON_DOWN_LEFT,
		ENEMY_CANNON_DOWN_RIGHT,
		ENEMY_CANNON_UP,
		ENEMY_1,
		ENEMY_KAMIKAZE,
		ENEMY_FURBY,
		ENEMY_FINAL4_EYE,
		ENEMY_POWERUP,
		ENEMY_SHIP1,
		ENEMY_SHIP2,
		ENEMY_SHIP3,
		ENEMY_SHIP4,
		ENEMY_TURRET,
		ENEMY_FINAL1_SHOOT,
		ENEMY_ASTEROID,
		ENEMY_TRASH1,
		ENEMY_TRASH2,
		ENEMY_TRASH3,
		ENEMY_TRASH4,
		ENEMY_TRASH5,
		ENEMY_SALTARIN,
		ENEMY_CASCO,
		ENEMY_EGG,
		ENEMY_UGLYGUY,
		ENEMY_1_BIS,
		ENEMY_SHIP2_BIS,
		ENEMY_SHIP3_BIS,
		ENEMY_SALTARIN_BIS,
		ENEMY_CASCO_BIS,
		ENEMY_EGG_BIS,
		ENEMY_UGLYGUY_BIS,
		ENEMY_SHIP1_LEVEL7,
		ENEMY_SHIP2_LEVEL7,
		ENEMY_SHIP3_LEVEL7,
		ENEMY_SHIP4_LEVEL7,
		ENEMY_TURRET_LEVEL7,
		ENEMY_PACOSHIP_1,
		ENEMY_PACOSHIP_2,
		ENEMY_FINAL1_LEVEL7_UL,
		ENEMY_FINAL1_LEVEL7_UR,
		ENEMY_FINAL1_LEVEL7_DL,
		ENEMY_FINAL1_LEVEL7_DR
	};

	unsigned char behavior_types[]=
	{
		BEHAV_DO_NOTHING, //ENEMY_EYE
		BEHAV_SHOOT_TARGET_LEFT, //ENEMY_CANNON_DOWN_LEFT
		BEHAV_SHOOT_TARGET_RIGHT, //ENEMY_CANNON_DOWN_RIGHT
		BEHAV_SHOOT_TARGET, //ENEMY_CANNON_UP
		BEHAV_SHOOT_LEFT, //ENEMY_1
		BEHAV_DO_NOTHING, //ENEMY_KAMIKAZE
		BEHAV_DO_NOTHING, //ENEMY_FURBY
		BEHAV_DO_NOTHING, //ENEMY_FINAL4_EYE
		BEHAV_POWERUP, //ENEMY_POWERUP
		BEHAV_DO_NOTHING, //ENEMY_SHIP1
		BEHAV_SHOOT_LEFT_Y, //ENEMY_SHIP2
		BEHAV_DO_NOTHING, //ENEMY_SHIP3
		BEHAV_SHOOT_LEFT_WAIT, //ENEMY_SHIP4
		BEHAV_TURRET, //ENEMY_TURRET
		BEHAV_DO_NOTHING, //ENEMY_FINAL1_SHOOT
		BEHAV_ASTEROID, //ENEMY_ASTEROID
		BEHAV_DO_NOTHING, //ENEMY_TRASH1
		BEHAV_DO_NOTHING, //ENEMY_TRASH2
		BEHAV_DO_NOTHING, //ENEMY_TRASH3
		BEHAV_DO_NOTHING, //ENEMY_TRASH4
		BEHAV_DO_NOTHING, //ENEMY_TRASH5
		BEHAV_SALTARIN, //ENEMY_SALTARIN
		BEHAV_CASCO, //ENEMY_CASCO
		BEHAV_EGG, //ENEMY_EGG
		BEHAV_UGLYGUY, //ENEMY_UGLYGUY
		BEHAV_SHOOT_LEFT_WAIT, //ENEMY_1_BIS
		BEHAV_SHOOT_LEFT_Y, //ENEMY_SHIP2_BIS
		BEHAV_DO_NOTHING, //ENEMY_SHIP3_BIS
		BEHAV_SALTARIN_BIS, //ENEMY_SALTARIN_BIS
		BEHAV_CASCO_BIS, //ENEMY_CASCO_BIS
		BEHAV_EGG, //ENEMY_EGG_BIS
		BEHAV_UGLYGUY, //ENEMY_UGLYGUY_BIS
		BEHAV_DO_NOTHING, //ENEMY_SHIP1_LEVEL7
		BEHAV_SHOOT_LEFT_Y, //ENEMY_SHIP2_LEVEL7
		BEHAV_DO_NOTHING, //ENEMY_SHIP3_LEVEL7
		BEHAV_SHOOT_LEFT_WAIT, //ENEMY_SHIP4_LEVEL7
		BEHAV_TURRET, //ENEMY_TURRET_LEVEL7
		BEHAV_DO_NOTHING, //ENEMY_PACOSHIP_1
		BEHAV_FOLLOW, //ENEMY_PACOSHIP_2
		BEHAV_FINAL1_L7, //ENEMY_FINAL1_LEVEL7_UL
		BEHAV_FOLLOW, //ENEMY_FINAL1_LEVEL7_UR
		BEHAV_FOLLOW, //ENEMY_FINAL1_LEVEL7_DL
		BEHAV_FOLLOW, //ENEMY_FINAL1_LEVEL7_DR
	};




unsigned char fenemy_defeat;		// Have we beaten it?
unsigned char map_xpos;
unsigned char map_displacement;  // Displacement in tile: 0000YYXX, where XX is the displacement in pixels (0, 1==2, 2==4, 3==6), and YY is the displacement in chars (0-2).
//ATTENTION
//this is normally found in main.c of Main ram

#include <arch/zx.h>
#include <input.h>
#include <stdlib.h>//standard library
#include <string.h>
//#include <compress/aplib.h>
#include <compress/zx7.h>



#include "ram6.h"



void main(void)
{
}



